"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
# TDG

# 追加
import os
import sys
sys.setrecursionlimit(10 ** 9)

from shutil import copyfile

# 自動生成
from setuptools import setup

VERSIONS = '0.0.2'

APP = ['gui/main.py']
APP_NAME = 'ternary_diagram'
DATA_FILES = [
    ('img', ['gui/img/w_o_z.png', 'gui/img/w_z.png'])
]

lib_path = os.path.join(os.environ['CONDA_PREFIX'], 'lib')
dylib_files = [os.path.join(lib_path, f) for f in os.listdir(lib_path) if '.dylib' in f]
frameworks_path = 'dist/' + APP_NAME + '.app/Contents/Frameworks'

PKGS = ['pandas', 'numpy', 'matplotlib', 'element_recognition', 'ternary_diagram']

OPTIONS = {
    'argv_emulation': False,
    'packages': PKGS,
    'iconfile': 'gui/icon/ternary_diagram.icns',
    'plist':{
        'PyRuntimeLocations':[
            '@executable_path/../Frameworks/libpython3.8.dylib',
            os.path.join(lib_path, 'libpython3.8.dylib'),
        ],
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Making ternary diagram.",
        'CFBundleIdentifier': "com.yu-9824.osx.ternary_diagram",
        'CFBundleVersion': VERSIONS,
        'CFBundleShortVersionString': VERSIONS,
        'NSHumanReadableCopyright': u"Copyright © 2020, yu-9824, All Rights Reserved"
    },
    # 'frameworks': dylib_files,
}

setup(
    name=APP_NAME,
    author='yu-9824',
    version=VERSIONS,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

{copyfile(f, os.path.join(frameworks_path, os.path.basename(f))) for f in dylib_files}
