"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
# 追加
import os
import sys
sys.setrecursionlimit(10 ** 9)

lib_path = '/Users/ryojikanno/.pyenv/versions/anaconda3-2019.03/envs/TD/lib'
dylib_files = [os.path.join(lib_path, f) for f in os.listdir(lib_path) if '.dylib' in f]
# print(dylib_files)

# 自動生成
from setuptools import setup


APP = ['gui/main.py']
DATA_FILES = [
    ('img', ['gui/img/w_o_z.png', 'gui/img/w_z.png'])
]

PKGS = ['pandas', 'numpy', 'matplotlib', 'element_recognition', 'ternary_diagram']

OPTIONS = {
    'argv_emulation':True,
    'packages': PKGS,
    'iconfile': 'gui/icon/ternary_diagram.icns',
    'plist':{
        'PyRuntimeLocations':[
            # '@executable_path/../Frameworks/libpython3.7m.dylib',
            '@executable_path/../Frameworks/libpython3.7.dylib',
            '/Users/ryojikanno/.pyenv/versions/anaconda3-2019.03/envs/TD/lib/libpython3.7m.dylib',
            # '@executable_path/../Frameworks/libffi.6.dylib',
        ],
    },
    'frameworks': dylib_files
}

setup(
    name='ternary_diagram_gui',
    author='yu-9824',
    version='0.0.1',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
